### ISSUE TITLE
Implement Enforcer class

### ISSUE THREAD

**Issue by akirill0v** [evrone/casbin-ruby#16]
Implement Enforcer class (`lib/casbin/enforcer.rb`) methods and tests

**Comment by jokius** [comment]
I take this one.

**Comment by jokius** [comment]
It depends on `ManagementEnforcer`, [#18](https://github.com/evrone/casbin-ruby/issues/18)

**Comment by jokius** [comment]
https://github.com/evrone/casbin-ruby/pull/24
