### ISSUE TITLE
Implement ManagementEnforcer class

### ISSUE THREAD

**Issue by akirill0v** [evrone/casbin-ruby#18]
Implement ManagementEnforcer class (`lib/casbin/management_enforcer.rb`) and tests

**Comment by evgeniy-r** [comment]
I depends on `InternalEnforcer`, https://github.com/evrone/casbin-ruby/pull/20

**Comment by vk26** [comment]
I take this one.

**Comment by jokius** [comment]
https://github.com/evrone/casbin-ruby/pull/23
